language: node_js
dist: trusty
node_js: stable
before_script:
- npm install --silent bower polymer-cli
- ./node_modules/.bin/bower install --silent
addons:
  sauce_connect: true
script:
- npm run lint
- ./node_modules/.bin/polymer test --plugin sauce --job-name "auth-dialogs:${TRAVIS_BRANCH}" --build-number=${TRAVIS_BUILD_NUMBER}
branches:
  only:
    - stage
    - develop
after_success:
  - node tasks/ci.js
