/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   auth-dialogs-mixin.html
 */

/// <reference path="../polymer/types/lib/utils/mixin.d.ts" />

declare namespace ArcBehaviors {


  /**
   * Contains a common function for authorization dialogs.
   *
   * Implementations should be named according to pattern `auth-dialog-[type]`.
   * The type is set on `auth-dialog-closed` event's `type` property.
   */
  function AuthDialogMixin<T extends new (...args: any[]) => {}>(base: T): T & AuthDialogMixinConstructor;

  interface AuthDialogMixinConstructor {
    new(...args: any[]): AuthDialogMixin;
  }

  interface AuthDialogMixin {

    /**
     * True if the dialog is opened.
     */
    opened: boolean|null|undefined;
    connectedCallback(): void;
    disconnectedCallback(): void;
    _onDialogClosed(e: any): void;

    /**
     * Creates the `value` object to be passed to the `auth-dialog-closed` custom event.
     */
    _getValue(): void;
  }
}
