/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   auth-dialogs.html
 */

/// <reference path="auth-dialog-basic.d.ts" />
/// <reference path="auth-dialog-ntlm.d.ts" />

