/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   auth-dialog-ntlm.html
 */

/// <reference path="../polymer/types/polymer-element.d.ts" />
/// <reference path="../paper-input/paper-input.d.ts" />
/// <reference path="../paper-masked-input/paper-masked-input.d.ts" />
/// <reference path="authorization-dialog.d.ts" />
/// <reference path="auth-dialogs-mixin.d.ts" />

declare namespace UiElements {

  /**
   * Authorization dialogs for Advanced REST Client.
   *
   * ### Example
   *
   * ```html
   * <auth-dialog-ntlm username="test" password="test" domain="my-nt-domain"
   *  on-auth-dialog-closed="_authData" opened></auth-dialog-ntlm>
   * ```
   *
   * ### Styling
   *
   * See the [authorization-dialog.html](authorization-dialog.html) for styling options.
   */
  class AuthDialogNtlm extends
    ArcBehaviors.AuthDialogMixin(
    Polymer.Element) {

    /**
     * User login
     */
    username: string|null|undefined;

    /**
     * User password
     */
    password: string|null|undefined;

    /**
     * NT domain to login to.
     */
    domain: string|null|undefined;
    _getValue(): any;
  }
}

interface HTMLElementTagNameMap {
  "auth-dialog-ntlm": UiElements.AuthDialogNtlm;
}
