/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   src/AuthDialogsMixin.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.
// tslint:disable:no-any describes the API as best we are able today

export {AuthDialogsMixin};

declare namespace ArcBehaviors {


  /**
   * Contains a common function for authorization dialogs.
   *
   * Implementations should be named according to pattern `auth-dialog-[type]`.
   * The type is set on `auth-dialog-closed` event's `type` property.
   */
  function AuthDialogsMixin<T extends new (...args: any[]) => {}>(base: T): T & AuthDialogsMixinConstructor;

  interface AuthDialogsMixinConstructor {
    new(...args: any[]): AuthDialogsMixin;
  }

  interface AuthDialogsMixin {

    /**
     * Enables compatibility with Anypoint platform
     */
    compatibility: boolean|null|undefined;
    connectedCallback(): void;
    disconnectedCallback(): void;
    _onDialogClosed(e: any): void;

    /**
     * Creates the `value` object to be passed to the `auth-dialog-closed` custom event.
     */
    _getValue(): void;

    /**
     * Handler for value change of an input.
     */
    _inputHandler(e: CustomEvent|null): void;
  }
}

export {AuthDialogsMixinConstructor};
