/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   src/AuthDialogBasic.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.
// tslint:disable:no-any describes the API as best we are able today

import {AnypointDialog} from '@anypoint-web-components/anypoint-dialog/src/AnypointDialog.js';

import {AuthDialogsMixin} from './AuthDialogsMixin.js';

import {html, css} from 'lit-element';

export {AuthDialogBasic};

declare namespace UiElements {

  /**
   * Authorization dialogs for Advanced REST Client.
   */
  class AuthDialogBasic extends
    AuthDialogsMixin(
    Object) {

    /**
     * User login
     */
    username: string|null|undefined;

    /**
     * User password
     */
    password: string|null|undefined;
    _getValue(): any;
    render(): any;
  }
}
